import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const read = (relativePath) => fs.readFileSync(path.join(repoRoot, relativePath), "utf8");
const exists = (relativePath) => fs.existsSync(path.join(repoRoot, relativePath));

const envExample = read(".env.example");
const gitignore = read(".gitignore");
const configExample = read("config/hotel-monitor.example.json");
const runScript = read("scripts/run-api-mvp.ps1");
const verifyScript = read("scripts/verify-local.ps1");
const runOnceScript = read("scripts/run-once.ps1");
const automationTemplate = read("templates/automation-prompt.template.md");
const dailyPrompt = read("templates/daily-prompt.md");
const readme = read("README.md");
const quickstart = read("docs/quickstart.md");
const dataSources = read("docs/data-sources.md");
const flyaiSetup = read("docs/flyai-setup.md");
const amapSetup = read("docs/amap-setup.md");
const baiduSetup = read("docs/baidu-setup.md");
const automationSetup = read("docs/automation-setup.md");
const troubleshooting = read("docs/troubleshooting.md");
const installer = read("install.ps1");
const startHere = read("workbuddy-start-here.md");
const skill = read("skill/SKILL.md");
const appHtml = read("app/index.html");
const appJs = read("app/app.js");
const flyaiGuide = read("app/flyai-guide.html");
const amapGuide = read("app/amap-guide.html");
const baiduGuide = read("app/baidu-guide.html");

assert.match(gitignore, /^data\/$/m, "API 原始数据目录必须被忽略");
assert.match(gitignore, /^config\/hotel-monitor\.json$/m, "本地私有配置必须被忽略");

assert.match(envExample, /^FLYAI_API_KEY=replace_with_your_flyai_key$/m, "env 示例应包含 FlyAI Key 占位符");
assert.match(envExample, /^AMAP_API_KEY=replace_with_your_amap_key$/m, "env 示例应包含高德 Key 占位符");
assert.match(envExample, /^BAIDU_MAP_AK=replace_with_your_baidu_ak$/m, "env 示例应包含百度 AK 占位符");
assert.doesNotMatch(envExample, /\b(sk-[A-Za-z0-9]{10,}|[A-Za-z0-9_-]{32,})\b/, "env 示例不能包含真实 Key");

const config = JSON.parse(configExample);
assert.equal(config.dataSources.primaryMap, "amap", "高德应是主地图源");
assert.equal(config.dataSources.price, "flyai", "FlyAI 应是价格源");
assert.equal(config.dataSources.reputation, "baidu", "百度应是口碑补充源");
assert.ok(config.discovery.radiusMeters >= 1000, "配置应包含半径");
assert.ok(config.discovery.maxCandidates >= 10, "配置应包含候选池上限");
assert.equal(config.baidu.enabled, true, "默认应启用百度补充");
assert.ok(config.baidu.enrichTopN >= 1, "配置应包含百度补充数量");
assert.equal(config.baidu.cacheEnabled, true, "默认应启用百度缓存");
assert.equal(config.baidu.cacheDirectory, "data/cache/baidu", "百度缓存应保存在本地 data/cache/baidu");
assert.ok(config.baidu.cacheTtlDays >= 1, "配置应包含百度缓存有效天数");
assert.ok(config.baidu.dailyCallLimit >= 0, "配置应包含百度每日调用上限");
assert.equal(config.flyai.enabled, true, "默认应启用 FlyAI 价格源");
assert.ok(config.flyai.requestDelayMs >= 0, "配置应包含 FlyAI 请求间隔");
assert.ok(config.flyai.maxRetries >= 0, "配置应包含 FlyAI 重试次数");
assert.equal(config.tierRules.coreRadiusMeters, 2000, "配置应包含核心竞品半径");
assert.equal(config.tierRules.pricePressureRatio, 0.75, "配置应包含价格压力比例");
assert.equal(config.tierRules.qualityRatingThreshold, 4.7, "配置应包含品质评分阈值");
assert.equal(config.tierRules.includeAlternativeLodging, true, "配置应包含替代住宿策略");
assert.equal(config.history.enabled, true, "默认应启用历史对比");
assert.equal(config.history.directory, "data/history", "历史快照应保存在本地 data/history");
assert.ok(Array.isArray(config.discovery.excludeNameKeywords), "配置应包含剔除关键词");

assert.ok(exists("scripts/run-api-mvp.ps1"), "应该提供三源组合运行脚本");
assert.ok(exists("scripts/verify-local.ps1"), "应该提供零额度本地验收脚本");
assert.ok(exists("scripts/run-once.ps1"), "应该提供安全单次运行脚本");
assert.match(runScript, /AMAP_API_KEY/, "组合脚本必须从环境变量读取高德 Key");
assert.match(runScript, /BAIDU_MAP_AK/, "组合脚本必须从环境变量读取百度 AK");
assert.match(runScript, /FLYAI_API_KEY/, "组合脚本必须从环境变量读取 FlyAI Key");
assert.match(runScript, /v5\/place\/text/, "组合脚本应调用高德文本检索");
assert.match(runScript, /v5\/place\/around/, "组合脚本应调用高德周边检索");
assert.match(runScript, /place\/v2\/search/, "组合脚本应调用百度地点检索");
assert.match(runScript, /place\/v2\/detail/, "组合脚本应调用百度地点详情");
assert.match(runScript, /search-hotel/, "组合脚本应调用 FlyAI 酒店搜索");
assert.match(runScript, /comp_tier/, "组合脚本应输出竞品分层字段");
assert.match(runScript, /api-combo-latest-report-input\.md/, "组合脚本应生成最新组合数据输入");
assert.match(runScript, /RoomType/, "组合脚本应把房型写入日报输入");
assert.match(runScript, /Adults/, "组合脚本应把成人数写入日报输入");
assert.match(runScript, /CompetitorCount/, "组合脚本应把竞对数量写入日报输入");
assert.match(runScript, /data\\history|data\/history/, "组合脚本应写入本地历史目录");
assert.match(runScript, /New-HistorySnapshot/, "组合脚本应生成历史快照");
assert.match(runScript, /Yesterday Comparison/, "组合脚本应输出昨日对比章节");
assert.match(runScript, /Get-PreviousHistorySnapshot/, "组合脚本应读取上一份同口径历史");
assert.match(runScript, /Compare-HistorySnapshots/, "组合脚本应计算历史对比");
assert.match(runScript, /Get-TierRules/, "组合脚本应读取可配置分层规则");
assert.match(runScript, /pricePressureRatio/, "组合脚本应支持价格压力阈值");
assert.match(runScript, /qualityRatingThreshold/, "组合脚本应支持品质评分阈值");
assert.match(runScript, /includeAlternativeLodging/, "组合脚本应支持替代住宿策略");
assert.match(runScript, /Select-FinalCandidates/, "组合脚本应按竞对数量、价格和排序收口最终竞对");
assert.match(runScript, /ReportedCandidateCount/, "组合脚本应输出实际竞对数量");
assert.match(runScript, /Get-BaiduSettings/, "组合脚本应读取百度缓存和限额配置");
assert.match(runScript, /Test-BaiduAkRequired/, "组合脚本应按百度配置判断是否需要 BAIDU_MAP_AK");
assert.match(runScript, /Read-BaiduCacheEntry/, "组合脚本应读取百度缓存");
assert.match(runScript, /Write-BaiduCacheEntry/, "组合脚本应写入百度缓存");
assert.match(runScript, /dailyCallLimit/, "组合脚本应支持百度每日调用上限");
assert.match(runScript, /Baidu Usage/, "组合脚本应输出百度使用状态");
assert.match(runScript, /Get-FlyAISettings/, "组合脚本应读取 FlyAI 调用配置");
assert.match(runScript, /New-FlyAIStats/, "组合脚本应统计 FlyAI 状态");
assert.match(runScript, /FlyAI Usage/, "组合脚本应输出 FlyAI 使用状态");
assert.match(runScript, /fliggy_status/, "组合脚本应输出价格状态");
assert.match(runScript, /fliggy_price_quality/, "组合脚本应输出价格质量");
assert.doesNotMatch(runScript, /\b(sk-[A-Za-z0-9]{10,}|[A-Za-z0-9_-]{40,})\b/, "组合脚本不能包含真实 Key");
assert.match(verifyScript, /run-api-mvp\.ps1.*-DryRun/s, "本地验收脚本应只跑 DryRun");
assert.match(verifyScript, /NetworkCallsToAmapFlyAIBaidu: 0/, "本地验收脚本应标记三源正式调用为 0");
assert.match(verifyScript, /ReadyForDryRun/, "本地验收脚本应输出 DryRun readiness");
assert.match(verifyScript, /ReadyForFormalRun/, "本地验收脚本应输出正式运行 readiness");
assert.match(verifyScript, /ConfigPath/, "本地验收脚本应支持指定配置路径");
assert.match(verifyScript, /SkipNodeTests/, "本地验收脚本应支持跳过 Node 测试");
assert.match(verifyScript, /secret scan/, "本地验收脚本应包含敏感信息扫描");
assert.match(runOnceScript, /\[switch\]\$Formal/, "单次运行脚本必须默认非正式采集");
assert.match(runOnceScript, /ReadyForDryRun/, "单次运行脚本应检查 DryRun readiness");
assert.match(runOnceScript, /ReadyForFormalRun/, "单次运行脚本应检查正式运行 readiness");
assert.match(runOnceScript, /run-api-mvp\.ps1/, "单次运行脚本应调用组合采集脚本");
assert.match(runOnceScript, /-DryRun/, "单次运行脚本默认应传递 DryRun");
assert.match(runOnceScript, /FormalCollection: \$formalCollection/, "单次运行报告应标明是否正式采集");
assert.doesNotMatch(runOnceScript, /\b(sk-[A-Za-z0-9]{10,}|[A-Za-z0-9_-]{40,})\b/, "单次运行脚本不能包含真实 Key");

assert.match(automationTemplate, /run-once\.ps1/, "自动化模板应运行安全单次入口");
assert.match(automationTemplate, /-Formal/, "自动化模板应通过 -Formal 做正式采集");
assert.match(automationTemplate, /ReadyForFormalRun|readiness|BlockingIssues/, "自动化模板应说明 readiness 阻塞处理");
assert.match(automationTemplate, /是否必需.*readiness/s, "自动化模板应说明 Key 必需性由 readiness 判断");
assert.match(automationTemplate, /高德/, "自动化模板应说明高德角色");
assert.match(automationTemplate, /百度/, "自动化模板应说明百度角色");
assert.match(automationTemplate, /FlyAI\/飞猪/, "自动化模板应说明 FlyAI 角色");
assert.match(automationTemplate, /百度省额度模式/, "自动化模板应说明百度省额度模式");
assert.match(automationTemplate, /百度关闭、补充数量为 0 或每日上限为 0/, "自动化模板应把主动关闭百度视为可解释状态");

assert.match(dailyPrompt, /高德/, "日报提示词应分析高德数据");
assert.match(dailyPrompt, /百度/, "日报提示词应分析百度口碑");
assert.match(dailyPrompt, /品质压力/, "日报提示词应输出品质压力");
assert.match(dailyPrompt, /评论数/, "日报提示词应关注评论数");
assert.match(dailyPrompt, /Yesterday Comparison/, "日报提示词应优先使用昨日对比");
assert.match(dailyPrompt, /谁调价了/, "日报提示词应回答谁调价了");
assert.match(dailyPrompt, /Tier Rules/, "日报提示词应尊重分层规则");
assert.match(dailyPrompt, /Baidu Usage/, "日报提示词应说明百度缓存和额度状态");
assert.match(dailyPrompt, /FlyAI Usage/, "日报提示词应说明 FlyAI 价格源状态");
assert.match(dailyPrompt, /查询口径/, "日报提示词应要求输出查询口径");
assert.match(dailyPrompt, /RoomType/, "日报提示词应使用房型字段");
assert.match(dailyPrompt, /Adults/, "日报提示词应使用住客数字段");
assert.match(dailyPrompt, /CompetitorCount/, "日报提示词应使用竞对数量字段");

assert.match(readme, /高德/, "README 应说明高德主地图源");
assert.match(readme, /百度/, "README 应说明百度口碑补充");
assert.match(readme, /https:\/\/lbs\.amap\.com\/api\/webservice\/create-project-and-key/, "README 应提供高德 Key 获取说明");
assert.match(readme, /https:\/\/lbsyun\.baidu\.com\/index\.php\?title=FAQ%2FobtainAK/, "README 应提供百度 AK 获取说明");
assert.match(readme, /data\/history/, "README 应说明历史快照目录");
assert.match(readme, /data\/cache\/baidu/, "README 应说明百度缓存目录");
assert.match(readme, /dailyCallLimit/, "README 应说明百度每日调用上限");
assert.match(readme, /百度省额度模式/, "README 应说明向导里的一键百度省额度模式");
assert.match(readme, /BAIDU_MAP_AK/, "README 应说明百度 AK 条件");
assert.match(readme, /最终监控并进入日报\/历史的竞对数量/, "README 应说明 competitorCount 是最终输出数量");
assert.match(readme, /候选池上限.*收口/s, "README 应说明 maxCandidates 是候选池上限");
assert.match(readme, /requestDelayMs/, "README 应说明 FlyAI 请求间隔");
assert.match(readme, /maxRetries/, "README 应说明 FlyAI 重试次数");
assert.match(readme, /tierRules/, "README 应说明可配置分层规则");
assert.match(readme, /app\/flyai-guide\.html/, "README 应提供 FlyAI 本地引导页");
assert.match(readme, /app\/amap-guide\.html/, "README 应提供高德本地引导页");
assert.match(readme, /app\/baidu-guide\.html/, "README 应提供百度本地引导页");
assert.match(readme, /docs\/automation-setup\.md/, "README 应提供 Automation 设置文档");
assert.match(readme, /给 WorkBuddy 的一句话/, "README 应提供醒目的 WorkBuddy 复制入口");
assert.match(readme, /请阅读 workbuddy-start-here\.md，并按步骤帮我部署酒店竞对每日监控 API 组合版。/, "README 的 WorkBuddy 入口应指向起步文件");
assert.match(readme, /scripts\\verify-local\.ps1|scripts\/verify-local\.ps1/, "README 应说明本地验收脚本");
assert.match(readme, /scripts\\run-once\.ps1|scripts\/run-once\.ps1/, "README 应说明安全单次运行脚本");
assert.match(readme, /install\.ps1/, "README 应说明先跑本地体检");
assert.match(readme, /data\/setup-check-latest\.md/, "README 应说明体检报告路径");
assert.match(readme, /ReadyForDryRun/, "README 应说明 DryRun readiness");
assert.match(readme, /ReadyForFormalRun/, "README 应说明正式运行 readiness");
assert.match(readme, /BlockingIssues/, "README 应说明阻塞项摘要");
assert.match(readme, /不调用高德、FlyAI 或百度 API/, "README 应说明体检不消耗额度");
assert.match(quickstart, /app\/flyai-guide\.html/, "快速开始应提供 FlyAI 本地引导页");
assert.match(quickstart, /app\/amap-guide\.html/, "快速开始应提供高德本地引导页");
assert.match(quickstart, /app\/baidu-guide\.html/, "快速开始应提供百度本地引导页");
assert.match(quickstart, /docs\/automation-setup\.md/, "快速开始应提供 Automation 设置文档");
assert.match(quickstart, /给 WorkBuddy 的一句话/, "快速开始应提供醒目的 WorkBuddy 复制入口");
assert.match(quickstart, /请阅读 workbuddy-start-here\.md，并按步骤帮我部署酒店竞对每日监控 API 组合版。/, "快速开始的 WorkBuddy 入口应指向起步文件");
assert.match(quickstart, /scripts\\verify-local\.ps1|scripts\/verify-local\.ps1/, "快速开始应说明本地验收脚本");
assert.match(quickstart, /scripts\\run-once\.ps1|scripts\/run-once\.ps1/, "快速开始应说明安全单次运行脚本");
assert.match(quickstart, /install\.ps1/, "快速开始应说明先跑本地体检");
assert.match(quickstart, /data\/setup-check-latest\.md/, "快速开始应说明体检报告路径");
assert.match(quickstart, /ReadyForDryRun/, "快速开始应说明 DryRun readiness");
assert.match(quickstart, /ReadyForFormalRun/, "快速开始应说明正式运行 readiness");
assert.match(quickstart, /BlockingIssues/, "快速开始应说明阻塞项摘要");
assert.match(quickstart, /BAIDU_MAP_AK/, "快速开始应说明百度 AK 条件");
assert.match(quickstart, /百度省额度模式/, "快速开始应说明向导里的一键百度省额度模式");
assert.match(quickstart, /最终进入日报和历史对比的竞对数量/, "快速开始应说明竞对数量含义");
assert.match(quickstart, /不会调用高德、FlyAI 或百度 API/, "快速开始应说明体检不消耗额度");
assert.match(startHere, /data\/setup-check-latest\.md/, "WorkBuddy 入口应读取体检报告");
assert.match(startHere, /不得调用高德、FlyAI 或百度 API/, "WorkBuddy 入口应强调体检不调用 API");
assert.match(startHere, /docs\/automation-setup\.md/, "WorkBuddy 入口应读取 Automation 设置文档");
assert.match(startHere, /scripts\\verify-local\.ps1|scripts\/verify-local\.ps1/, "WorkBuddy 入口应说明本地验收脚本");
assert.match(startHere, /百度省额度模式/, "WorkBuddy 入口应提示可一键进入百度省额度模式");
assert.match(skill, /data\/setup-check-latest\.md/, "Skill 应读取体检报告");
assert.match(skill, /RepairConfigFromExample/, "Skill 应说明旧配置修复");
assert.match(skill, /docs\/automation-setup\.md/, "Skill 应读取 Automation 设置文档");
assert.match(skill, /每天 07:30/, "Skill 应说明每天 07:30 自动化");
assert.match(skill, /scripts\/verify-local\.ps1/, "Skill 应说明本地验收脚本");
assert.match(skill, /dailyCallLimit/, "Skill 应说明百度 AK 是否必需取决于配置");
assert.match(skill, /必需 Key/, "Skill 单次运行提示应区分必需 Key");
assert.match(dataSources, /高德作为主地图源/, "数据源文档应说明高德主地图源");
assert.match(dataSources, /百度作为口碑补充源/, "数据源文档应说明百度口碑补充");
assert.match(dataSources, /本地历史库/, "数据源文档应说明本地历史库");
assert.match(dataSources, /pricePressureRatio/, "数据源文档应说明价格压力阈值");
assert.match(dataSources, /cacheEnabled/, "数据源文档应说明百度缓存");
assert.match(dataSources, /dailyCallLimit/, "数据源文档应说明百度每日调用上限");
assert.match(dataSources, /discovery\.maxCandidates/, "数据源文档应说明候选池上限");
assert.match(dataSources, /discovery\.competitorCount/, "数据源文档应说明最终竞对数量");
assert.match(dataSources, /maxPrice.*价格缺失或脱敏/s, "数据源文档应说明价格筛选边界");
assert.match(dataSources, /FlyAI Usage/, "数据源文档应说明 FlyAI 使用状态");
assert.match(dataSources, /MaskedPrices/, "数据源文档应说明 FlyAI 脱敏价格统计");
assert.match(flyaiSetup, /AMAP_API_KEY/, "设置文档应说明高德环境变量");
assert.match(flyaiSetup, /BAIDU_MAP_AK/, "设置文档应说明百度环境变量");
assert.match(flyaiSetup, /create-project-and-key/, "设置文档应提供高德 Key 官方入口");
assert.match(flyaiSetup, /obtainAK/, "设置文档应提供百度 AK 官方入口");
assert.match(flyaiSetup, /docs\/amap-setup\.md/, "FlyAI 设置文档应链接高德独立引导");
assert.match(flyaiSetup, /docs\/baidu-setup\.md/, "FlyAI 设置文档应链接百度独立引导");
assert.match(flyaiSetup, /run-once\.ps1 -Formal/, "FlyAI 设置文档正式运行应走安全入口");
assert.match(flyaiSetup, /ReadyForFormalRun/, "FlyAI 设置文档应说明正式运行 readiness");
assert.match(flyaiSetup, /dailyCallLimit.*0/s, "FlyAI 设置文档应说明百度限额 0 时可选");
assert.match(amapSetup, /AMAP_API_KEY/, "高德引导应说明环境变量");
assert.match(amapSetup, /Web 服务/, "高德引导应说明 Web 服务 Key");
assert.match(amapSetup, /create-project-and-key/, "高德引导应提供官方入口");
assert.match(baiduSetup, /BAIDU_MAP_AK/, "百度引导应说明环境变量");
assert.match(baiduSetup, /dailyCallLimit/, "百度引导应说明每日调用上限");
assert.match(baiduSetup, /不会要求 `BAIDU_MAP_AK`/, "百度引导应说明限额 0 时不要求 AK");
assert.match(baiduSetup, /DryRun 不调用百度/, "百度引导应说明 DryRun 不消耗额度");
assert.match(automationSetup, /每天 07:30/, "Automation 文档应说明每天 07:30");
assert.match(automationSetup, /30 7 \* \* \*/, "Automation 文档应提供 cron 表达式");
assert.match(automationSetup, /MiniMax 2\.5|低成本内置模型/, "Automation 文档应建议低成本内置模型");
assert.match(automationSetup, /ClawBot/, "Automation 文档应说明 ClawBot 推送");
assert.match(automationSetup, /automation-prompt\.template\.md/, "Automation 文档应使用自动化提示词模板");
assert.match(automationSetup, /run-once\.ps1 -Formal/, "Automation 文档应要求通过 run-once -Formal 正式采集");
assert.match(automationSetup, /不要启用 OTA 浏览器自动化/, "Automation 文档应禁止 OTA 网页自动化");
assert.match(automationSetup, /codebuddy\.cn\/docs\/workbuddy\/.*Automation-Guide/, "Automation 文档应链接官方自动化说明");
assert.match(automationSetup, /codebuddy\.ai\/docs\/ide\/Platform-integration\/weixinbot-guide/, "Automation 文档应链接官方 ClawBot 说明");

assert.match(appHtml, /id="radiusMeters"/, "向导应收集半径");
assert.match(appHtml, /id="baiduEnrichTopN"/, "向导应收集百度补充数量");
assert.match(appHtml, /id="historyEnabled"/, "向导应收集是否启用历史对比");
assert.match(appHtml, /id="historyDirectory"/, "向导应收集历史目录");
assert.match(appHtml, /id="baiduEnabled"/, "向导应收集百度接口开关");
assert.match(appHtml, /id="baiduCacheEnabled"/, "向导应收集百度缓存开关");
assert.match(appHtml, /id="baiduDailyCallLimit"/, "向导应收集百度每日调用上限");
assert.match(appHtml, /百度关闭或每日上限为 0/, "向导应说明省额度时百度 AK 可选");
assert.match(appHtml, /id="baiduQuotaSafeMode"/, "向导应提供一键百度省额度模式");
assert.match(appHtml, /id="baiduCacheTtlDays"/, "向导应收集百度缓存天数");
assert.match(appHtml, /id="baiduCacheDirectory"/, "向导应收集百度缓存目录");
assert.match(appHtml, /id="flyaiEnabled"/, "向导应收集 FlyAI 开关");
assert.match(appHtml, /id="flyaiRequestDelayMs"/, "向导应收集 FlyAI 请求间隔");
assert.match(appHtml, /id="flyaiMaxRetries"/, "向导应收集 FlyAI 重试次数");
assert.match(appHtml, /id="coreRadiusMeters"/, "向导应收集核心竞品半径");
assert.match(appHtml, /id="pricePressureRatio"/, "向导应收集价格压力比例");
assert.match(appHtml, /id="qualityRatingThreshold"/, "向导应收集品质评分阈值");
assert.match(appHtml, /id="includeAlternativeLodging"/, "向导应收集替代住宿策略");
assert.match(appHtml, /key-guide/, "向导应包含 API Key 获取引导区域");
assert.match(appHtml, /flyai-guide\.html/, "向导应提供 FlyAI 本地引导页");
assert.match(appHtml, /amap-guide\.html/, "向导应提供高德本地引导页");
assert.match(appHtml, /baidu-guide\.html/, "向导应提供百度本地引导页");
assert.match(appHtml, /https:\/\/flyai\.open\.fliggy\.com\/#ability/, "向导应提供 FlyAI Key 获取入口");
assert.match(appHtml, /https:\/\/lbs\.amap\.com\/api\/webservice\/create-project-and-key/, "向导应提供高德 Key 获取入口");
assert.match(appHtml, /https:\/\/lbsyun\.baidu\.com\/index\.php\?title=FAQ%2FobtainAK/, "向导应提供百度 AK 获取入口");
assert.match(appHtml, /setx FLYAI_API_KEY/, "向导应提供 FlyAI 环境变量命令");
assert.match(appHtml, /setx AMAP_API_KEY/, "向导应提供高德环境变量命令");
assert.match(appHtml, /setx BAIDU_MAP_AK/, "向导应提供百度环境变量命令");
assert.match(appJs, /AMAP_API_KEY/, "向导运行提示应提示高德 Key");
assert.match(appJs, /BAIDU_MAP_AK/, "向导运行提示应提示百度 AK");
assert.match(appJs, /history/, "向导应生成历史配置");
assert.match(appJs, /tierRules/, "向导应生成分层规则配置");
assert.match(appJs, /dailyCallLimit/, "向导应生成百度每日调用上限配置");
assert.match(appJs, /baiduQuotaSafeMode/, "向导应实现一键百度省额度模式");
assert.match(appJs, /baiduDailyCallLimit"\)\.value = "0"/, "百度省额度模式应把每日调用上限设为 0");
assert.match(appJs, /baiduEnrichTopN"\)\.value = "0"/, "百度省额度模式应把百度补充数量设为 0");
assert.match(appJs, /baiduEnabled"\)\.value = "false"/, "百度省额度模式应关闭百度真实调用");
assert.match(appJs, /cacheDirectory/, "向导应生成百度缓存目录配置");
assert.match(appJs, /requestDelayMs/, "向导应生成 FlyAI 请求间隔配置");
assert.match(appJs, /maxRetries/, "向导应生成 FlyAI 重试配置");
assert.match(appJs, /查询口径（用户配置）：入住\[CheckIn\]/, "向导下载的日报提示词应区分用户配置口径");
assert.match(appJs, /价格源实际应用：\[Applied Query Scope 摘要\]/, "向导下载的日报提示词应输出价格源实际口径");
assert.match(appJs, /RoomType/, "向导下载的日报提示词应使用房型字段");
assert.match(appJs, /CompetitorCount/, "向导下载的日报提示词应使用竞对数量字段");
assert.match(appJs, /Baidu Usage/, "向导下载的日报提示词应说明百度用量状态");
assert.match(appJs, /run-once\.ps1/, "向导生成的自动化提示词应使用安全单次入口");
assert.match(appJs, /-Formal/, "向导生成的自动化提示词应通过 -Formal 做正式采集");
assert.match(appJs, /buildPushInstructions/, "向导生成的自动化提示词应按推送模式分支");
assert.match(appJs, /pushMode === "clawbot"/, "向导应支持 ClawBot 推送模式");
assert.match(appJs, /pushMode === "wecom"/, "向导应支持企业微信推送模式");
assert.match(appJs, /pushMode === "none"/, "向导应支持只保存本地模式");
assert.match(appJs, /push-wecom\.ps1/, "向导生成的自动化提示词应包含企业微信推送脚本");
assert.match(appJs, /百度省额度模式/, "向导生成的自动化提示词应说明百度省额度模式");
assert.match(appJs, /百度关闭、补充数量为 0 或每日上限为 0/, "向导生成的自动化提示词应把主动关闭百度视为可解释状态");
assert.match(appJs, /最终回复必须包含/, "向导生成的自动化提示词应约束最终回复");
assert.match(appJs, /查询口径/, "向导生成的自动化提示词应要求回复查询口径");
assert.match(appJs, /推送状态/, "向导生成的自动化提示词应要求回复推送状态");
assert.match(appJs, /flyai-guide\.html/, "运行提示应指向 FlyAI 本地引导页");
assert.match(appJs, /amap-guide\.html/, "运行提示应指向高德本地引导页");
assert.match(appJs, /baidu-guide\.html/, "运行提示应指向百度本地引导页");

assert.match(installer, /flyai-guide\.html/, "安装脚本应提示 FlyAI 本地引导页");
assert.match(installer, /amap-guide\.html/, "安装脚本应提示高德本地引导页");
assert.match(installer, /baidu-guide\.html/, "安装脚本应提示百度本地引导页");
assert.match(installer, /setup-check-latest\.md/, "安装脚本应生成本地体检报告");
assert.match(installer, /Get-FormalRequirements/, "安装脚本应按配置判断正式运行必需项");
assert.match(installer, /BAIDU_MAP_AK requirement/, "安装脚本应输出百度 AK 是否必需");
assert.match(installer, /NetworkCalls: 0/, "安装脚本体检报告应标记零网络调用");
assert.match(installer, /does not call Amap, FlyAI or Baidu APIs/, "安装脚本应说明不调用三方 API");
assert.match(installer, /RepairConfigFromExample/, "安装脚本应支持修复旧配置结构");
assert.match(installer, /Add-MissingConfigProperties/, "安装脚本应通过补字段方式修复配置");
assert.match(installer, /\.bak-\$timestamp/, "安装脚本修复配置前应备份旧文件");
assert.match(troubleshooting, /run-once\.ps1 -Formal/, "排障文档重新运行正式采集应走安全入口");
assert.match(troubleshooting, /BlockingIssues/, "排障文档应提示查看阻塞项");

assert.match(flyaiGuide, /FLYAI_API_KEY/, "FlyAI 本地引导页应说明环境变量");
assert.match(flyaiGuide, /flyai.open.fliggy.com/, "FlyAI 本地引导页应提供官方入口");
assert.match(flyaiGuide, /Get-Command flyai/, "FlyAI 本地引导页应说明 CLI 自检");
assert.match(amapGuide, /AMAP_API_KEY/, "高德本地引导页应说明环境变量");
assert.match(amapGuide, /地点文本检索/, "高德本地引导页应说明检索能力");
assert.match(amapGuide, /DryRun 不调用高德/, "高德本地引导页应说明 DryRun");
assert.match(baiduGuide, /BAIDU_MAP_AK/, "百度本地引导页应说明环境变量");
assert.match(baiduGuide, /dailyCallLimit/, "百度本地引导页应说明调用上限");
assert.match(baiduGuide, /DryRun 不调用百度/, "百度本地引导页应说明 DryRun 不耗额度");
