import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const read = (relativePath) => fs.readFileSync(path.join(repoRoot, relativePath), "utf8");
const exists = (relativePath) => fs.existsSync(path.join(repoRoot, relativePath));

const envExample = read(".env.example");
const gitignore = read(".gitignore");
const configExample = read("config/hotel-monitor.example.json");
const runScript = read("scripts/run-api-mvp.ps1");
const automationTemplate = read("templates/automation-prompt.template.md");
const dailyPrompt = read("templates/daily-prompt.md");
const readme = read("README.md");
const dataSources = read("docs/data-sources.md");
const flyaiSetup = read("docs/flyai-setup.md");
const appHtml = read("app/index.html");
const appJs = read("app/app.js");

assert.match(gitignore, /^data\/$/m, "API 原始数据目录必须被忽略");
assert.match(gitignore, /^config\/hotel-monitor\.json$/m, "本地私有配置必须被忽略");

assert.match(envExample, /^FLYAI_API_KEY=replace_with_your_flyai_key$/m, "env 示例应包含 FlyAI Key 占位符");
assert.match(envExample, /^AMAP_API_KEY=replace_with_your_amap_key$/m, "env 示例应包含高德 Key 占位符");
assert.match(envExample, /^BAIDU_MAP_AK=replace_with_your_baidu_ak$/m, "env 示例应包含百度 AK 占位符");
assert.doesNotMatch(envExample, /\b(sk-[A-Za-z0-9]{10,}|[A-Za-z0-9_-]{32,})\b/, "env 示例不能包含真实 Key");

const config = JSON.parse(configExample);
assert.equal(config.dataSources.primaryMap, "amap", "高德应是主地图源");
assert.equal(config.dataSources.price, "flyai", "FlyAI 应是价格源");
assert.equal(config.dataSources.reputation, "baidu", "百度应是口碑补充源");
assert.ok(config.discovery.radiusMeters >= 1000, "配置应包含半径");
assert.ok(config.discovery.maxCandidates >= 10, "配置应包含候选池上限");
assert.equal(config.baidu.enabled, true, "默认应启用百度补充");
assert.ok(config.baidu.enrichTopN >= 1, "配置应包含百度补充数量");
assert.equal(config.baidu.cacheEnabled, true, "默认应启用百度缓存");
assert.equal(config.baidu.cacheDirectory, "data/cache/baidu", "百度缓存应保存在本地 data/cache/baidu");
assert.ok(config.baidu.cacheTtlDays >= 1, "配置应包含百度缓存有效天数");
assert.ok(config.baidu.dailyCallLimit >= 0, "配置应包含百度每日调用上限");
assert.equal(config.flyai.enabled, true, "默认应启用 FlyAI 价格源");
assert.ok(config.flyai.requestDelayMs >= 0, "配置应包含 FlyAI 请求间隔");
assert.ok(config.flyai.maxRetries >= 0, "配置应包含 FlyAI 重试次数");
assert.equal(config.tierRules.coreRadiusMeters, 2000, "配置应包含核心竞品半径");
assert.equal(config.tierRules.pricePressureRatio, 0.75, "配置应包含价格压力比例");
assert.equal(config.tierRules.qualityRatingThreshold, 4.7, "配置应包含品质评分阈值");
assert.equal(config.tierRules.includeAlternativeLodging, true, "配置应包含替代住宿策略");
assert.equal(config.history.enabled, true, "默认应启用历史对比");
assert.equal(config.history.directory, "data/history", "历史快照应保存在本地 data/history");
assert.ok(Array.isArray(config.discovery.excludeNameKeywords), "配置应包含剔除关键词");

assert.ok(exists("scripts/run-api-mvp.ps1"), "应该提供三源组合运行脚本");
assert.match(runScript, /AMAP_API_KEY/, "组合脚本必须从环境变量读取高德 Key");
assert.match(runScript, /BAIDU_MAP_AK/, "组合脚本必须从环境变量读取百度 AK");
assert.match(runScript, /FLYAI_API_KEY/, "组合脚本必须从环境变量读取 FlyAI Key");
assert.match(runScript, /v5\/place\/text/, "组合脚本应调用高德文本检索");
assert.match(runScript, /v5\/place\/around/, "组合脚本应调用高德周边检索");
assert.match(runScript, /place\/v2\/search/, "组合脚本应调用百度地点检索");
assert.match(runScript, /place\/v2\/detail/, "组合脚本应调用百度地点详情");
assert.match(runScript, /search-hotel/, "组合脚本应调用 FlyAI 酒店搜索");
assert.match(runScript, /comp_tier/, "组合脚本应输出竞品分层字段");
assert.match(runScript, /api-combo-latest-report-input\.md/, "组合脚本应生成最新组合数据输入");
assert.match(runScript, /data\\history|data\/history/, "组合脚本应写入本地历史目录");
assert.match(runScript, /New-HistorySnapshot/, "组合脚本应生成历史快照");
assert.match(runScript, /Yesterday Comparison/, "组合脚本应输出昨日对比章节");
assert.match(runScript, /Get-PreviousHistorySnapshot/, "组合脚本应读取上一份同口径历史");
assert.match(runScript, /Compare-HistorySnapshots/, "组合脚本应计算历史对比");
assert.match(runScript, /Get-TierRules/, "组合脚本应读取可配置分层规则");
assert.match(runScript, /pricePressureRatio/, "组合脚本应支持价格压力阈值");
assert.match(runScript, /qualityRatingThreshold/, "组合脚本应支持品质评分阈值");
assert.match(runScript, /includeAlternativeLodging/, "组合脚本应支持替代住宿策略");
assert.match(runScript, /Get-BaiduSettings/, "组合脚本应读取百度缓存和限额配置");
assert.match(runScript, /Read-BaiduCacheEntry/, "组合脚本应读取百度缓存");
assert.match(runScript, /Write-BaiduCacheEntry/, "组合脚本应写入百度缓存");
assert.match(runScript, /dailyCallLimit/, "组合脚本应支持百度每日调用上限");
assert.match(runScript, /Baidu Usage/, "组合脚本应输出百度使用状态");
assert.match(runScript, /Get-FlyAISettings/, "组合脚本应读取 FlyAI 调用配置");
assert.match(runScript, /New-FlyAIStats/, "组合脚本应统计 FlyAI 状态");
assert.match(runScript, /FlyAI Usage/, "组合脚本应输出 FlyAI 使用状态");
assert.match(runScript, /fliggy_status/, "组合脚本应输出价格状态");
assert.match(runScript, /fliggy_price_quality/, "组合脚本应输出价格质量");
assert.doesNotMatch(runScript, /\b(sk-[A-Za-z0-9]{10,}|[A-Za-z0-9_-]{40,})\b/, "组合脚本不能包含真实 Key");

assert.match(automationTemplate, /run-api-mvp\.ps1/, "自动化模板应运行组合脚本");
assert.match(automationTemplate, /高德/, "自动化模板应说明高德角色");
assert.match(automationTemplate, /百度/, "自动化模板应说明百度角色");
assert.match(automationTemplate, /FlyAI\/飞猪/, "自动化模板应说明 FlyAI 角色");

assert.match(dailyPrompt, /高德/, "日报提示词应分析高德数据");
assert.match(dailyPrompt, /百度/, "日报提示词应分析百度口碑");
assert.match(dailyPrompt, /品质压力/, "日报提示词应输出品质压力");
assert.match(dailyPrompt, /评论数/, "日报提示词应关注评论数");
assert.match(dailyPrompt, /Yesterday Comparison/, "日报提示词应优先使用昨日对比");
assert.match(dailyPrompt, /谁调价了/, "日报提示词应回答谁调价了");
assert.match(dailyPrompt, /Tier Rules/, "日报提示词应尊重分层规则");
assert.match(dailyPrompt, /Baidu Usage/, "日报提示词应说明百度缓存和额度状态");
assert.match(dailyPrompt, /FlyAI Usage/, "日报提示词应说明 FlyAI 价格源状态");

assert.match(readme, /高德/, "README 应说明高德主地图源");
assert.match(readme, /百度/, "README 应说明百度口碑补充");
assert.match(readme, /https:\/\/lbs\.amap\.com\/api\/webservice\/create-project-and-key/, "README 应提供高德 Key 获取说明");
assert.match(readme, /https:\/\/lbsyun\.baidu\.com\/index\.php\?title=FAQ%2FobtainAK/, "README 应提供百度 AK 获取说明");
assert.match(readme, /data\/history/, "README 应说明历史快照目录");
assert.match(readme, /data\/cache\/baidu/, "README 应说明百度缓存目录");
assert.match(readme, /dailyCallLimit/, "README 应说明百度每日调用上限");
assert.match(readme, /requestDelayMs/, "README 应说明 FlyAI 请求间隔");
assert.match(readme, /maxRetries/, "README 应说明 FlyAI 重试次数");
assert.match(readme, /tierRules/, "README 应说明可配置分层规则");
assert.match(dataSources, /高德作为主地图源/, "数据源文档应说明高德主地图源");
assert.match(dataSources, /百度作为口碑补充源/, "数据源文档应说明百度口碑补充");
assert.match(dataSources, /本地历史库/, "数据源文档应说明本地历史库");
assert.match(dataSources, /pricePressureRatio/, "数据源文档应说明价格压力阈值");
assert.match(dataSources, /cacheEnabled/, "数据源文档应说明百度缓存");
assert.match(dataSources, /dailyCallLimit/, "数据源文档应说明百度每日调用上限");
assert.match(dataSources, /FlyAI Usage/, "数据源文档应说明 FlyAI 使用状态");
assert.match(dataSources, /MaskedPrices/, "数据源文档应说明 FlyAI 脱敏价格统计");
assert.match(flyaiSetup, /AMAP_API_KEY/, "设置文档应说明高德环境变量");
assert.match(flyaiSetup, /BAIDU_MAP_AK/, "设置文档应说明百度环境变量");
assert.match(flyaiSetup, /create-project-and-key/, "设置文档应提供高德 Key 官方入口");
assert.match(flyaiSetup, /obtainAK/, "设置文档应提供百度 AK 官方入口");

assert.match(appHtml, /id="radiusMeters"/, "向导应收集半径");
assert.match(appHtml, /id="baiduEnrichTopN"/, "向导应收集百度补充数量");
assert.match(appHtml, /id="historyEnabled"/, "向导应收集是否启用历史对比");
assert.match(appHtml, /id="historyDirectory"/, "向导应收集历史目录");
assert.match(appHtml, /id="baiduEnabled"/, "向导应收集百度接口开关");
assert.match(appHtml, /id="baiduCacheEnabled"/, "向导应收集百度缓存开关");
assert.match(appHtml, /id="baiduDailyCallLimit"/, "向导应收集百度每日调用上限");
assert.match(appHtml, /id="baiduCacheTtlDays"/, "向导应收集百度缓存天数");
assert.match(appHtml, /id="baiduCacheDirectory"/, "向导应收集百度缓存目录");
assert.match(appHtml, /id="flyaiEnabled"/, "向导应收集 FlyAI 开关");
assert.match(appHtml, /id="flyaiRequestDelayMs"/, "向导应收集 FlyAI 请求间隔");
assert.match(appHtml, /id="flyaiMaxRetries"/, "向导应收集 FlyAI 重试次数");
assert.match(appHtml, /id="coreRadiusMeters"/, "向导应收集核心竞品半径");
assert.match(appHtml, /id="pricePressureRatio"/, "向导应收集价格压力比例");
assert.match(appHtml, /id="qualityRatingThreshold"/, "向导应收集品质评分阈值");
assert.match(appHtml, /id="includeAlternativeLodging"/, "向导应收集替代住宿策略");
assert.match(appHtml, /key-guide/, "向导应包含 API Key 获取引导区域");
assert.match(appHtml, /https:\/\/flyai\.open\.fliggy\.com\/#ability/, "向导应提供 FlyAI Key 获取入口");
assert.match(appHtml, /https:\/\/lbs\.amap\.com\/api\/webservice\/create-project-and-key/, "向导应提供高德 Key 获取入口");
assert.match(appHtml, /https:\/\/lbsyun\.baidu\.com\/index\.php\?title=FAQ%2FobtainAK/, "向导应提供百度 AK 获取入口");
assert.match(appHtml, /setx FLYAI_API_KEY/, "向导应提供 FlyAI 环境变量命令");
assert.match(appHtml, /setx AMAP_API_KEY/, "向导应提供高德环境变量命令");
assert.match(appHtml, /setx BAIDU_MAP_AK/, "向导应提供百度环境变量命令");
assert.match(appJs, /AMAP_API_KEY/, "向导运行提示应提示高德 Key");
assert.match(appJs, /BAIDU_MAP_AK/, "向导运行提示应提示百度 AK");
assert.match(appJs, /history/, "向导应生成历史配置");
assert.match(appJs, /tierRules/, "向导应生成分层规则配置");
assert.match(appJs, /dailyCallLimit/, "向导应生成百度每日调用上限配置");
assert.match(appJs, /cacheDirectory/, "向导应生成百度缓存目录配置");
assert.match(appJs, /requestDelayMs/, "向导应生成 FlyAI 请求间隔配置");
assert.match(appJs, /maxRetries/, "向导应生成 FlyAI 重试配置");
